Revert r68847. It breaks the build on non-Darwin targets, with this message from the assembler:
Error: unknown pseudo-op: `.debug_inlined'


git-svn-id: https://llvm.org/svn/llvm-project@68863 91177308-0d34-0410-b5e6-96231b3b80d8