tests: Mark expected FreeBSD failures due to pr16697
These fail due to:
error: Expression can't be run, because there is no JIT compiled function


git-svn-id: https://llvm.org/svn/llvm-project@187072 91177308-0d34-0410-b5e6-96231b3b80d8