Throw a NoClassDefFoundError instead of a LinkageError if resolving a class does not work.
git-svn-id: https://llvm.org/svn/llvm-project@89759 91177308-0d34-0410-b5e6-96231b3b80d8