Register enumconstantdecls in their appropriate scope and check for conflicts. This emits these diagnostics:
t.c:4:14: error: redefinition of 'a'
enum foo22 { a, b };
             ^
t.c:3:5: error: previous definition is here
int a;
    ^
t.c:8:17: error: redefinition of enumerator 'b'
enum foo23 { c, b };
                ^
t.c:4:17: error: previous definition is here
enum foo22 { a, b };
                ^
4 diagnostics generated.


for:

int a;
enum foo22 { a, b };
enum foo23 { c, b };


git-svn-id: https://llvm.org/svn/llvm-project@39302 91177308-0d34-0410-b5e6-96231b3b80d8