Make ProcessDeclAttributes walk the declarator structure pulling decl attributes out of the various places they can hide.  This makes us correctly reject things like this:
t.c:2:22: error: mode attribute only supported for integer and floating-point types
  int **__attribute((mode(HI)))* i32;
                     ^

because you can't make a pointer be HImode.



git-svn-id: https://llvm.org/svn/llvm-project@52876 91177308-0d34-0410-b5e6-96231b3b80d8