Fix via-file-asm test failure on windows
The windows target does not support using an external assembler so
the test case was failing with this error:

error: there is no external assembler that can be used on this platform

The test was updated to always explicitly pass a target that has
both an interal and external assembler.


git-svn-id: https://llvm.org/svn/llvm-project@196854 91177308-0d34-0410-b5e6-96231b3b80d8